# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_paymentplan_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('payment_plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.PaymentPlan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
