# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160127_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.PaymentPlan'),
        ),
    ]
